trigger:
- main  # Cambia "main" si usas otra rama como "master" o "develop"

pool:
  vmImage: 'windows-latest'    

steps:
# Paso 1: Ejecutar las pruebas con Maven
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'  # Asegúrate de que el pom.xml esté en la raíz
    options: '-B'            # Modo batch para Maven
    goals: 'clean test'      # Ejecuta las pruebas
