trigger:
- main  # Cambia "main" si usas otra rama como "master" o "develop"

pool:
  vmImage: 'windows-latest'    

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'  # Especifica la versión de Java que necesitas
    jdkArchitecture: 'x64'  # Arquitectura de Java, puede ser x86 o x64

- task: Maven@3
  inputs:
    mavenVersionOption: 'Default'
    mavenPomFile: 'pom.xml'
    goals: 'clean compile'

# Paso 2: Ejecutar Maven
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'    # Asegúrate de que el pom.xml esté en la raíz
    options: '-B'             # Habilita modo batch para Maven
    goals: 'clean test'       # Combina compile y test en un solo paso
